language: node_js
node_js:
- '10.9'
branches:
  only:
  - master
addons:
  chrome: stable
before_script:
- npm install -g @angular/cli
cache:
  yarn: true
  directories:
  - node_modules
script:
- ng build --prod
notifications:
  email: bhanukamgamage@gmail.com

before_install:
- openssl aes-256-cbc -K $encrypted_48b3bd1ee5e4_key -iv $encrypted_48b3bd1ee5e4_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host ec2-52-221-17-136.ap-southeast-1.compute.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key ubuntu@ec2-52-221-17-136.ap-southeast-1.compute.amazonaws.com pwd


after_success:
  - sudo apt-get update
  - cd /var/www/bhanukagamage.com
  - git pull origin master
  - ng build --prod
  