language: node_js
node_js:
- '12.0'
branches:
  only:
  - master
addons:
  chrome: stable
before_script:
- npm install -g @angular/cli@latest
cache:
  yarn: true
  directories:
  - node_modules
script:
- ng build --prod
notifications:
  email: bhanukamgamage@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- echo -e "Host 157.245.184.69\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_sucess:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh -i ./deploy_key root@157.245.184.69 'bash -s' < deploy.sh
