language: node_js
node_js:
- '10.9'
branches:
  only:
  - master
addons:
  chrome: stable
before_script:
- npm install -g @angular/cli
cache:
  yarn: true
  directories:
  - node_modules
script:
- ng build --prod
notifications:
  email: bhanukamgamage@gmail.com

before_install:
- echo -e "Host ec2-52-221-17-136.ap-southeast-1.compute.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_sucess:
  - ssh -i ./deploy_key ubuntu@ec2-52-221-17-136.ap-southeast-1.compute.amazonaws.com 'bash -s' < deploy.sh