language: node_js
node_js:
- '10.9'
branches:
  only:
  - master
addons:
  chrome: stable
before_script:
- npm install -g @angular/cli
cache:
  yarn: true
  directories:
  - node_modules
script:
- ng build --prod
notifications:
  email: bhanukamgamage@gmail.com

after_sucess:
  - ssh root@157.245.184.69 'bash -s' < deploy.sh